version: '3.8'

services:
  universidades-api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - red_universidades
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/universidadesdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: universidadesdb
    networks:
      - red_universidades

networks:
  red_universidades:
