apiVersion: v1
kind: Service
metadata:
  name: universidades-api
  namespace: universidades
spec:
  type: NodePort
  selector:
    app: universidades-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
